/**
 * The fictional rentals of the demo. The agencies, the addresses and the texts are invented, and the
 * photos are public domain interiors (see `public/photos/CREDITS.md`), not the flats described.
 *
 * Some texts carry, on purpose, what a real portal receives every day: a deposit of two months, fees
 * charged to the tenant, a guarantee above the legal limit, a missing energy rating. They give the
 * tenant something to ask the regulations about, and the reviews of later phases something to find.
 */

import type { Agency, RentalListing } from "./catalogue";

const ILLA_HOMES: Agency = { name: "Illa Homes", initials: "IH" };
const FINQUES_PORTAL: Agency = { name: "Finques Portal", initials: "FP" };
const CASTELLANA_RENTALS: Agency = { name: "Castellana Rentals", initials: "CR" };
const TURIA_ALQUILERES: Agency = { name: "Turia Alquileres", initials: "TA" };
const GIRALDA_HOGAR: Agency = { name: "Giralda Hogar", initials: "GH" };
const COSTA_LUZ: Agency = { name: "Costa Luz Inmobiliaria", initials: "CL" };
const RIA_ETXEAK: Agency = { name: "Ría Etxeak", initials: "RE" };
const PRIVATE_LANDLORD: Agency = { name: "Particular", initials: "P" };

const photos = (...names: string[]) => names.map((name) => `/photos/${name}.webp`);

export const CATALOGUE: RentalListing[] = [
  {
    id: "palma-santa-catalina-2h",
    title: "Piso luminoso de 2 habitaciones en Santa Catalina",
    municipality: "Palma",
    region: "Illes Balears",
    neighbourhood: "Santa Catalina",
    priceEurMonth: 1350,
    usableSurfaceM2: 78,
    rooms: 2,
    bathrooms: 1,
    floor: "3ª planta",
    energyRating: "E",
    features: ["Ascensor", "Balcón", "Amueblado", "Aire acondicionado"],
    agency: ILLA_HOMES,
    photos: photos("living-2", "kitchen-1", "bedroom-5", "bathroom-2"),
    description:
      "Piso reformado en pleno Santa Catalina, a cinco minutos del mercado y del paseo marítimo. Salón con balcón a la calle, cocina independiente equipada, dos dormitorios dobles y baño con ducha.\n\nAlquiler de larga duración. Renta de 1.350 €/mes, gastos de comunidad incluidos; suministros a cargo del inquilino. Fianza: dos mensualidades.",
    publishedAt: "2026-09-26",
  },
  {
    id: "palma-son-armadams-3h-vistas",
    title: "Ático de 3 habitaciones con terraza y vistas al mar",
    municipality: "Palma",
    region: "Illes Balears",
    neighbourhood: "Son Armadams",
    priceEurMonth: 1900,
    usableSurfaceM2: 105,
    rooms: 3,
    bathrooms: 2,
    floor: "Ático",
    energyRating: "C",
    features: ["Terraza", "Vistas al mar", "Ascensor", "Parking", "Aire acondicionado"],
    agency: ILLA_HOMES,
    photos: photos("facade-6", "living-9", "kitchen-8", "bedroom-1", "bathroom-1"),
    description:
      "Ático con terraza de 25 m² y vistas a la bahía de Palma. Tres dormitorios, dos baños completos, cocina abierta al salón y plaza de parking incluida.\n\nRenta de 1.900 €/mes. Gastos de comunidad (90 €/mes) incluidos en la renta; agua, luz e internet a cargo del inquilino. Fianza legal de una mensualidad. Los honorarios de la agencia los paga la propiedad.",
    publishedAt: "2026-09-24",
  },
  {
    id: "soller-centro-2h",
    title: "Casa de pueblo de 2 habitaciones en el centro de Sóller",
    municipality: "Sóller",
    region: "Illes Balears",
    neighbourhood: "Centro",
    priceEurMonth: 1250,
    usableSurfaceM2: 85,
    rooms: 2,
    bathrooms: 1,
    floor: "Planta baja y primera",
    energyRating: "En trámite",
    features: ["Patio", "Calefacción", "Amueblado"],
    agency: ILLA_HOMES,
    photos: photos("facade-3", "living-4", "kitchen-3", "bedroom-8"),
    description:
      "Casa mallorquina en una calle tranquila del centro, a dos minutos de la plaza y del tranvía al puerto. Salón comedor con chimenea, cocina con salida a un patio, dos dormitorios en la planta superior.\n\nRenta de 1.250 €/mes más gastos. Certificado energético en trámite. Honorarios de agencia: una mensualidad más IVA a cargo del inquilino.",
    publishedAt: "2026-09-19",
  },
  {
    id: "alcudia-port-1h",
    title: "Apartamento de 1 habitación junto al puerto de Alcúdia",
    municipality: "Alcúdia",
    region: "Illes Balears",
    neighbourhood: "Port d'Alcúdia",
    priceEurMonth: 950,
    usableSurfaceM2: 55,
    rooms: 1,
    bathrooms: 1,
    floor: "1ª planta",
    energyRating: "D",
    features: ["Piscina comunitaria", "Balcón", "Amueblado"],
    agency: PRIVATE_LANDLORD,
    photos: photos("living-3", "kitchen-7", "bedroom-6", "bathroom-4"),
    description:
      "Apartamento amueblado a 300 metros de la playa, en una urbanización con piscina comunitaria. Salón con cocina americana, dormitorio doble y baño.\n\nAlquiler anual, no vacacional. Renta de 950 €/mes. Se requiere fianza de un mes y garantía adicional de tres meses.",
    publishedAt: "2026-09-12",
  },
  {
    id: "barcelona-gracia-2h",
    title: "Piso con balcones de 2 habitaciones en Gràcia",
    municipality: "Barcelona",
    region: "Cataluña",
    neighbourhood: "Gràcia",
    priceEurMonth: 1450,
    usableSurfaceM2: 70,
    rooms: 2,
    bathrooms: 1,
    floor: "2ª planta",
    energyRating: "D",
    features: ["Balcón", "Calefacción", "Exterior"],
    agency: FINQUES_PORTAL,
    photos: photos("facade-4", "living-7", "kitchen-9", "bedroom-2", "bathroom-3"),
    description:
      "Piso exterior con dos balcones a una calle peatonal de Gràcia, cerca de la plaza del Sol y del metro de Fontana. Suelos hidráulicos originales, dos dormitorios, cocina reformada y baño con ducha.\n\nRenta de 1.450 €/mes. Fianza de una mensualidad, depositada en el INCASÒL. Comunidad incluida.",
    publishedAt: "2026-09-25",
  },
  {
    id: "barcelona-eixample-3h",
    title: "Piso señorial de 3 habitaciones en el Eixample",
    municipality: "Barcelona",
    region: "Cataluña",
    neighbourhood: "Eixample Dret",
    priceEurMonth: 2300,
    usableSurfaceM2: 110,
    rooms: 3,
    bathrooms: 2,
    floor: "Principal",
    energyRating: "B",
    features: ["Ascensor", "Aire acondicionado", "Calefacción", "Trastero"],
    agency: FINQUES_PORTAL,
    photos: photos("living-5", "kitchen-6", "bedroom-7", "bathroom-1", "facade-5"),
    description:
      "Piso modernista rehabilitado junto a paseo de Sant Joan: techos altos con molduras, tres dormitorios exteriores, dos baños y cocina office. Finca con ascensor y portería.\n\nRenta de 2.300 €/mes. Fianza de una mensualidad. Honorarios de agencia a cargo del inquilino: 10 % de la renta anual más IVA.",
    publishedAt: "2026-09-21",
  },
  {
    id: "barcelona-poblenou-loft",
    title: "Loft de 1 habitación en el Poblenou",
    municipality: "Barcelona",
    region: "Cataluña",
    neighbourhood: "Poblenou",
    priceEurMonth: 1300,
    usableSurfaceM2: 60,
    rooms: 1,
    bathrooms: 1,
    floor: "4ª planta",
    energyRating: "A",
    features: ["Ascensor", "Aire acondicionado", "Terraza", "Admite mascotas"],
    agency: FINQUES_PORTAL,
    photos: photos("living-1", "kitchen-2", "bedroom-4", "facade-9"),
    description:
      "Loft en un edificio de nueva construcción a diez minutos de la playa del Bogatell. Espacio diáfano con cocina integrada, dormitorio en altillo, terraza comunitaria y aerotermia.\n\nRenta de 1.300 €/mes, comunidad incluida. Fianza de una mensualidad. Cédula de habitabilidad vigente. Se admiten mascotas.",
    publishedAt: "2026-09-16",
  },
  {
    id: "girona-barri-vell-2h",
    title: "Piso de 2 habitaciones en el Barri Vell de Girona",
    municipality: "Girona",
    region: "Cataluña",
    neighbourhood: "Barri Vell",
    priceEurMonth: 950,
    usableSurfaceM2: 75,
    rooms: 2,
    bathrooms: 1,
    floor: "1ª planta",
    energyRating: null,
    features: ["Calefacción", "Amueblado"],
    agency: PRIVATE_LANDLORD,
    photos: photos("living-8", "kitchen-4", "bedroom-3", "facade-3"),
    description:
      "Piso con paredes de piedra en el casco antiguo, a un paso de la catedral y del río Onyar. Dos dormitorios, salón comedor y cocina independiente.\n\nRenta de 950 €/mes. Disponible a partir de octubre.",
    publishedAt: "2026-09-10",
  },
  {
    id: "madrid-malasana-1h",
    title: "Estudio reformado de 1 habitación en Malasaña",
    municipality: "Madrid",
    region: "Comunidad de Madrid",
    neighbourhood: "Malasaña",
    priceEurMonth: 1150,
    usableSurfaceM2: 48,
    rooms: 1,
    bathrooms: 1,
    floor: "3ª planta",
    energyRating: "E",
    features: ["Amueblado", "Aire acondicionado", "Exterior"],
    agency: CASTELLANA_RENTALS,
    photos: photos("living-6", "kitchen-5", "bedroom-5"),
    description:
      "Estudio exterior recién reformado en la calle más tranquila de Malasaña, a dos minutos del metro de Tribunal. Salón con cocina abierta, dormitorio independiente y baño con plato de ducha.\n\nRenta de 1.150 €/mes. Fianza de dos meses y una mensualidad por adelantado.",
    publishedAt: "2026-09-23",
  },
  {
    id: "madrid-chamberi-3h",
    title: "Piso familiar de 3 habitaciones en Chamberí",
    municipality: "Madrid",
    region: "Comunidad de Madrid",
    neighbourhood: "Chamberí",
    priceEurMonth: 2100,
    usableSurfaceM2: 95,
    rooms: 3,
    bathrooms: 2,
    floor: "5ª planta",
    energyRating: "C",
    features: ["Ascensor", "Calefacción", "Aire acondicionado", "Trastero"],
    agency: CASTELLANA_RENTALS,
    photos: photos("facade-5", "living-2", "kitchen-6", "bedroom-2", "bathroom-2"),
    description:
      "Piso luminoso junto a la plaza de Olavide: salón amplio, tres dormitorios, dos baños y cocina equipada. Calefacción central incluida en la comunidad.\n\nRenta de 2.100 €/mes, gastos de comunidad incluidos. Fianza legal de una mensualidad. Honorarios de gestión a cargo de la propiedad.",
    publishedAt: "2026-09-18",
  },
  {
    id: "madrid-lavapies-2h",
    title: "Piso de 2 habitaciones en Lavapiés",
    municipality: "Madrid",
    region: "Comunidad de Madrid",
    neighbourhood: "Lavapiés",
    priceEurMonth: 1200,
    usableSurfaceM2: 62,
    rooms: 2,
    bathrooms: 1,
    floor: "2ª planta",
    energyRating: null,
    features: ["Balcón", "Amueblado"],
    agency: PRIVATE_LANDLORD,
    photos: photos("living-4", "kitchen-9", "bedroom-8", "bathroom-3"),
    description:
      "Piso en corrala rehabilitada, a cinco minutos del metro de Lavapiés. Dos dormitorios, salón con balcón y cocina independiente.\n\nRenta de 1.200 €/mes. Fianza de un mes. Imprescindible nómina y aval bancario de seis meses de renta.",
    publishedAt: "2026-09-14",
  },
  {
    id: "valencia-ruzafa-2h",
    title: "Piso de 2 habitaciones con encanto en Ruzafa",
    municipality: "Valencia",
    region: "Comunitat Valenciana",
    neighbourhood: "Ruzafa",
    priceEurMonth: 1100,
    usableSurfaceM2: 80,
    rooms: 2,
    bathrooms: 1,
    floor: "1ª planta",
    energyRating: "D",
    features: ["Balcón", "Aire acondicionado", "Exterior"],
    agency: TURIA_ALQUILERES,
    photos: photos("facade-1", "living-3", "kitchen-1", "bedroom-6"),
    description:
      "Piso de finca antigua rehabilitada en el corazón de Ruzafa, a un paso del mercado. Techos altos, dos dormitorios dobles, salón con balcón y cocina equipada.\n\nRenta de 1.100 €/mes; comunidad incluida y suministros aparte. Fianza de una mensualidad. Los honorarios de la agencia los asume la propiedad.",
    publishedAt: "2026-09-22",
  },
  {
    id: "valencia-cabanyal-3h",
    title: "Casa de 3 habitaciones cerca de la playa en el Cabanyal",
    municipality: "Valencia",
    region: "Comunitat Valenciana",
    neighbourhood: "El Cabanyal",
    priceEurMonth: 1250,
    usableSurfaceM2: 90,
    rooms: 3,
    bathrooms: 2,
    floor: "Planta baja y primera",
    energyRating: "En trámite",
    features: ["Terraza", "Patio", "Admite mascotas"],
    agency: TURIA_ALQUILERES,
    photos: photos("living-9", "kitchen-8", "bedroom-1", "bathroom-4", "facade-8"),
    description:
      "Casa típica del Cabanyal con fachada de azulejo, a 400 metros de la playa de las Arenas. Tres dormitorios, dos baños, patio y terraza en la cubierta.\n\nRenta de 1.250 €/mes. Fianza de una mensualidad. Certificado energético en trámite. Se admiten mascotas.",
    publishedAt: "2026-09-08",
  },
  {
    id: "sevilla-triana-2h",
    title: "Piso de 2 habitaciones en Triana, junto al río",
    municipality: "Sevilla",
    region: "Andalucía",
    neighbourhood: "Triana",
    priceEurMonth: 950,
    usableSurfaceM2: 72,
    rooms: 2,
    bathrooms: 1,
    floor: "2ª planta",
    energyRating: "E",
    features: ["Ascensor", "Aire acondicionado"],
    agency: GIRALDA_HOGAR,
    photos: photos("living-7", "kitchen-3", "bedroom-3", "bathroom-2"),
    description:
      "Piso junto a la calle Betis, a dos minutos del puente de Triana. Salón comedor, dos dormitorios, cocina equipada y aire acondicionado por conductos.\n\nRenta de 950 €/mes, comunidad incluida. Fianza de una mensualidad.",
    publishedAt: "2026-09-17",
  },
  {
    id: "malaga-soho-1h",
    title: "Apartamento de 1 habitación en el Soho de Málaga",
    municipality: "Málaga",
    region: "Andalucía",
    neighbourhood: "Soho",
    priceEurMonth: 1100,
    usableSurfaceM2: 50,
    rooms: 1,
    bathrooms: 1,
    floor: "4ª planta",
    energyRating: "D",
    features: ["Ascensor", "Terraza", "Amueblado", "Aire acondicionado"],
    agency: COSTA_LUZ,
    photos: photos("facade-2", "living-6", "kitchen-7", "bedroom-4"),
    description:
      "Apartamento amueblado en el barrio de las artes, a cinco minutos del puerto y de la calle Larios. Salón con salida a terraza, dormitorio doble y baño con ducha.\n\nRenta de 1.100 €/mes. Fianza de una mensualidad. Gastos de gestión del contrato: 300 € a cargo del inquilino.",
    publishedAt: "2026-09-20",
  },
  {
    id: "bilbao-abando-3h",
    title: "Piso de 3 habitaciones en Abando, junto a la Gran Vía",
    municipality: "Bilbao",
    region: "País Vasco",
    neighbourhood: "Abando",
    priceEurMonth: 1400,
    usableSurfaceM2: 100,
    rooms: 3,
    bathrooms: 2,
    floor: "6ª planta",
    energyRating: "C",
    features: ["Ascensor", "Calefacción", "Exterior", "Trastero"],
    agency: RIA_ETXEAK,
    photos: photos("facade-7", "living-1", "kitchen-5", "bedroom-7", "bathroom-1"),
    description:
      "Piso exterior en una finca clásica de Abando, a un paso de la Gran Vía y del metro de Moyúa. Tres dormitorios, dos baños, cocina office y trastero.\n\nRenta de 1.400 €/mes; calefacción central incluida. Fianza de una mensualidad. Honorarios a cargo de la propiedad.",
    publishedAt: "2026-09-06",
  },
];
